//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.CommentWords = new HashSet<CommentWord>();
        }
    
        public int id { get; set; }
        public string fb_id { get; set; }
        public int post_id { get; set; }
        public int entity_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> score { get; set; }
        public bool scored { get; set; }
        public string message { get; set; }
        public bool splitted { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual ICollection<CommentWord> CommentWords { get; set; }
    }
}
