//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int id { get; set; }
        public string fb_id { get; set; }
        public int entity_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public bool scraped { get; set; }
        public string message { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
