//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public Word()
        {
            this.CommentWords = new HashSet<CommentWord>();
        }
    
        public int id { get; set; }
        public string word1 { get; set; }
        public bool stop { get; set; }
        public Nullable<int> stem_id { get; set; }
    
        public virtual ICollection<CommentWord> CommentWords { get; set; }
    }
}
